### ISSUE TITLE
Fix/improve what goes in channel and what goes in DM

### ISSUE THREAD

**Issue by max-mathieu** [jasonrhodes/hubot-cah#1]
hand / answers > always in DM
submit / choose > always in channel

**Comment by colestrode** [comment]
It would be great if we could use a private message (like you get from slackbot on /collapse ) instead of a DM. 

Though maybe this isn't possible? https://twitter.com/slackapi/status/565304367017099266

**Comment by max-mathieu** [comment]
Don't think we can
