### ISSUE TITLE
remove the "cah" from the command

### ISSUE THREAD

**Issue by max-mathieu** [jasonrhodes/hubot-cah#2]
We won't have too many scripts, let's make sure we can do `cbot submit x`

**Comment by colestrode** [comment]
This probably won't be accepted by the upstream, so we may not be able to feed in any other bug fixes if we do this

**Comment by max-mathieu** [comment]
We could make it an option, based on the team name maybe

And who cares about the upstream? :)

**Comment by jasonrhodes** [comment]
I don't care about the upstream really, BUT i think it's easier to just use `robot.hear` instead of `robot.respond` so we can drop the `cbot` part of the cah commands. :)

**Comment by max-mathieu** [comment]
Fair enough
